new TypeIt("#love", {
  speed: 50,
})
  .type('<h2>Here is a story about <strong>love</strong>…</h2><br>')
  .type('<span class="n">u&nbsp;</span><span class="o">=&nbsp;</span><span class="n">Girl</span><span class="p">(</span><span class="s2">"Tongtong🐒"</span><span class="p">)</span><br>')
  .type('<span class="n">i&nbsp;</span><span class="o">=&nbsp;</span><span class="n">Boy</span><span class="p">(</span><span class="s2">"Along🐍"</span><span class="p">)</span><br>')
  .type('<span class="p">#&nbsp;</span><a href="/since/">2022/05/03</a><span class="p">&nbsp;is&nbsp;a&nbsp;Special&nbsp;Day</span><br>')
  .type('<span class="k">from&nbsp;</span><span class="nn">datetime&nbsp;</span><span class="k">import&nbsp;</span><span class="n">date</span><br>')
  .type('<span class="n">anniversary&nbsp;</span><span class="o">=&nbsp;</span><span class="n">date</span><span class="p">(</span><span class="o">2022</span><span class="p">,&nbsp;</span><span class="o">05</span><span class="p">,&nbsp;</span><span class="o">03</span><span class="p">)</span><br>')
  .type('<span class="n">i</span><span class="o">.</span><span class="n">tell</span><span class="p">(</span><span class="n">u</span><span class="p">,&nbsp;</span><span class="s2">"I&nbsp;love&nbsp;U!"</span><span class="p">)</span><br>')
  .type('<span class="n">u</span><span class="o">.</span><span class="n">accept</span><span class="p">()</span><br>')
  .type('<span class="n">days&nbsp;</span><span class="o">=&nbsp;</span><span class="p">(</span><span class="n">date</span><span class="o">.</span><span class="n">today</span><span class="p">()&nbsp;</span><span class="o">-&nbsp;</span><span class="n">anniversary</span><span class="p">)</span><span class="o">.</span><span class="n">days</span><br>')
  .type('<span class="k">for&nbsp;</span><span class="n">day&nbsp;</span><span class="ow">in&nbsp;</span><span class="bp">range</span><span class="p">(</span><span class="n">days</span><span class="p">):</span><br>')
  .type('<span class="n">&nbsp;&nbsp;i</span><span class="o">.</span><span class="n">love</span><span class="p">(</span><span class="n">u</span><span class="p">)</span><br>')
  .type('<span class="n">&nbsp;&nbsp;i</span><span class="o">.</span><span class="n">miss</span><span class="p">(</span><span class="n">u</span><span class="p">)</span><br>')
  .type('<span class="n">&nbsp;&nbsp;i</span><span class="o">.</span><span class="n">kiss</span><span class="p">(</span><span class="n">u</span><span class="p">)</span><br>')
  .type('<span class="n">&nbsp;&nbsp;i</span><span class="o">.</span><span class="n">take_care_of</span><span class="p">(</span><span class="n">u</span><span class="p">)</span><br>')
  .type('<span class="p">#&nbsp;TODO:&nbsp;Our&nbsp;Future</span><br>')
  .type('<span class="n">is_hesitate&nbsp;</span><span class="o">=&nbsp;</span><span class="bp">True</span><br>')
  .type('<span class="k">while&nbsp;</span><span class="n">is_hesitate</span><span class="p">:</span><br>')
  .type('<span class="n">&nbsp;&nbsp;i&nbsp;</span><span class="o">=&nbsp;</span><span class="n">i</span><span class="o">.</span><span class="n">better</span><span class="p">()</span><br>')
  .type('<span class="n">&nbsp;&nbsp;i</span><span class="o">.</span><span class="n">wait_for</span><span class="p">(</span><span class="n">u</span><span class="p">)</span><br>')
  .type('<span class="n">&nbsp;&nbsp;is_hesitate&nbsp;</span><span class="o">=&nbsp;</span><span class="n">u</span><span class="o">.</span><span class="n">think_over</span><span class="p">()</span><br>')
  .type('<span class="p">#&nbsp;After&nbsp;a&nbsp;Romantic&nbsp;Wedding&nbsp;💒</span><br>')
  .type('<span class="n">we&nbsp;</span><span class="o">=&nbsp;</span><span class="n">i</span><span class="o">.</span><span class="n">marry</span><span class="p">(</span><span class="n">u</span><span class="p">);</span><br>')
  .type('<span class="k">while&nbsp;</span><span class="bp">True</span><span class="p">:</span><br>')
  .type('<span class="n">&nbsp;&nbsp;we</span><span class="o">.</span><span class="n">live_with</span><span class="p">(</span><span class="s2">"💗️"</span><span class="p">)</span><br>')
  .type('<span class="p">#&nbsp;Forever…</span>')
  .go();